/*
 * Santoral do Calendário Romano Geral de 1962 (rubricas de 1960).
 *
 * Cada entrada: [classe, cor, nome, marcas]
 *   classe: 1, 2, 3 (classes litúrgicas) ou 0 (simples comemoração)
 *   cor:    w branco, r vermelho, v roxo, b preto
 *   marcas: "L" festa do Senhor; "V" vigília; "IC" Imaculada Conceição;
 *           "AD" Fiéis Defuntos (não se celebra em domingo)
 * A primeira entrada de cada dia é a celebração própria; as seguintes,
 * comemorações.
 */
(function (root) {
  "use strict";

  var S = {
    // ───────────── JANEIRO ─────────────
    "01-05": [[0, "r", "S. Telésforo, Papa e Mártir"]],
    "01-11": [[0, "r", "S. Higino, Papa e Mártir"]],
    "01-14": [[3, "w", "S. Hilário, Bispo, Confessor e Doutor"], [0, "r", "S. Félix, Presbítero e Mártir"]],
    "01-15": [[3, "w", "S. Paulo, Primeiro Eremita, Confessor"], [0, "w", "S. Mauro, Abade"]],
    "01-16": [[3, "r", "S. Marcelo I, Papa e Mártir"]],
    "01-17": [[3, "w", "S. Antão, Abade"]],
    "01-18": [[0, "r", "S. Prisca, Virgem e Mártir"]],
    "01-19": [[0, "r", "Ss. Mário, Marta, Audifaz e Ábaco, Mártires"], [0, "r", "S. Canuto, Rei e Mártir"]],
    "01-20": [[3, "r", "Ss. Fabiano, Papa, e Sebastião, Mártires"]],
    "01-21": [[3, "r", "S. Inês, Virgem e Mártir"]],
    "01-22": [[3, "r", "Ss. Vicente e Anastácio, Mártires"]],
    "01-23": [[3, "w", "S. Raimundo de Penaforte, Confessor"], [0, "r", "S. Emerenciana, Virgem e Mártir"]],
    "01-24": [[3, "r", "S. Timóteo, Bispo e Mártir"]],
    "01-25": [[3, "w", "Conversão de S. Paulo, Apóstolo"], [0, "w", "S. Pedro, Apóstolo"]],
    "01-26": [[3, "r", "S. Policarpo, Bispo e Mártir"]],
    "01-27": [[3, "w", "S. João Crisóstomo, Bispo, Confessor e Doutor"]],
    "01-28": [[3, "w", "S. Pedro Nolasco, Confessor"], [0, "r", "S. Inês, Virgem e Mártir (segunda vez)"]],
    "01-29": [[3, "w", "S. Francisco de Sales, Bispo, Confessor e Doutor"]],
    "01-30": [[3, "r", "S. Martina, Virgem e Mártir"]],
    "01-31": [[3, "w", "S. João Bosco, Confessor"]],

    // ───────────── FEVEREIRO ─────────────
    "02-01": [[3, "r", "S. Inácio, Bispo e Mártir"]],
    "02-02": [[2, "w", "Purificação da Bem-aventurada Virgem Maria", "L"]],
    "02-03": [[0, "r", "S. Brás, Bispo e Mártir"]],
    "02-04": [[3, "w", "S. André Corsini, Bispo e Confessor"]],
    "02-05": [[3, "r", "S. Águeda, Virgem e Mártir"]],
    "02-06": [[3, "w", "S. Tito, Bispo e Confessor"], [0, "r", "S. Doroteia, Virgem e Mártir"]],
    "02-07": [[3, "w", "S. Romualdo, Abade"]],
    "02-08": [[3, "w", "S. João da Mata, Confessor"]],
    "02-09": [[3, "w", "S. Cirilo de Alexandria, Bispo, Confessor e Doutor"], [0, "r", "S. Apolônia, Virgem e Mártir"]],
    "02-10": [[3, "w", "S. Escolástica, Virgem"]],
    "02-11": [[3, "w", "Aparição da Imaculada Virgem Maria em Lourdes"]],
    "02-12": [[3, "w", "Os Sete Santos Fundadores da Ordem dos Servitas"]],
    "02-14": [[0, "r", "S. Valentim, Presbítero e Mártir"]],
    "02-15": [[0, "r", "Ss. Faustino e Jovita, Mártires"]],
    "02-18": [[0, "r", "S. Simeão, Bispo e Mártir"]],
    "02-22": [[2, "w", "Cátedra de S. Pedro, Apóstolo"], [0, "w", "S. Paulo, Apóstolo"]],
    "02-23": [[3, "w", "S. Pedro Damião, Bispo, Confessor e Doutor"]],
    "02-24": [[2, "r", "S. Matias, Apóstolo"]],
    "02-27": [[3, "w", "S. Gabriel de Nossa Senhora das Dores, Confessor"]],

    // ───────────── MARÇO ─────────────
    "03-04": [[3, "w", "S. Casimiro, Confessor"], [0, "r", "S. Lúcio I, Papa e Mártir"]],
    "03-06": [[3, "r", "Ss. Perpétua e Felicidade, Mártires"]],
    "03-07": [[3, "w", "S. Tomás de Aquino, Confessor e Doutor"]],
    "03-08": [[3, "w", "S. João de Deus, Confessor"]],
    "03-09": [[3, "w", "S. Francisca Romana, Viúva"]],
    "03-10": [[3, "r", "Os Quarenta Santos Mártires"]],
    "03-12": [[3, "w", "S. Gregório Magno, Papa, Confessor e Doutor"]],
    "03-17": [[3, "w", "S. Patrício, Bispo e Confessor"]],
    "03-18": [[3, "w", "S. Cirilo de Jerusalém, Bispo, Confessor e Doutor"]],
    "03-19": [[1, "w", "S. José, Esposo da Bem-aventurada Virgem Maria, Confessor"]],
    "03-21": [[3, "w", "S. Bento, Abade"]],
    "03-24": [[3, "w", "S. Gabriel Arcanjo"]],
    "03-25": [[1, "w", "Anunciação da Bem-aventurada Virgem Maria"]],
    "03-27": [[3, "w", "S. João Damasceno, Confessor e Doutor"]],
    "03-28": [[3, "w", "S. João de Capistrano, Confessor"]],

    // ───────────── ABRIL ─────────────
    "04-02": [[3, "w", "S. Francisco de Paula, Confessor"]],
    "04-04": [[3, "w", "S. Isidoro, Bispo, Confessor e Doutor"]],
    "04-05": [[3, "w", "S. Vicente Ferrer, Confessor"]],
    "04-11": [[3, "w", "S. Leão I, Papa, Confessor e Doutor"]],
    "04-13": [[3, "r", "S. Hermenegildo, Mártir"]],
    "04-14": [[3, "r", "S. Justino, Mártir"], [0, "r", "Ss. Tibúrcio, Valeriano e Máximo, Mártires"]],
    "04-17": [[0, "r", "S. Aniceto, Papa e Mártir"]],
    "04-21": [[3, "w", "S. Anselmo, Bispo, Confessor e Doutor"]],
    "04-22": [[3, "r", "Ss. Sotero e Caio, Papas e Mártires"]],
    "04-23": [[0, "r", "S. Jorge, Mártir"]],
    "04-24": [[3, "r", "S. Fidélis de Sigmaringa, Mártir"]],
    "04-25": [[2, "r", "S. Marcos, Evangelista"]],
    "04-26": [[3, "r", "Ss. Cleto e Marcelino, Papas e Mártires"]],
    "04-27": [[3, "w", "S. Pedro Canísio, Confessor e Doutor"]],
    "04-28": [[3, "w", "S. Paulo da Cruz, Confessor"]],
    "04-29": [[3, "r", "S. Pedro de Verona, Mártir"]],
    "04-30": [[3, "w", "S. Catarina de Sena, Virgem"]],

    // ───────────── MAIO ─────────────
    "05-01": [[1, "w", "S. José Operário, Esposo da Bem-aventurada Virgem Maria"]],
    "05-02": [[3, "w", "S. Atanásio, Bispo, Confessor e Doutor"]],
    "05-03": [[0, "r", "Ss. Alexandre, Evêncio e Teódulo, Mártires, e S. Juvenal"]],
    "05-04": [[3, "w", "S. Mônica, Viúva"]],
    "05-05": [[3, "w", "S. Pio V, Papa e Confessor"]],
    "05-07": [[3, "r", "S. Estanislau, Bispo e Mártir"]],
    "05-09": [[3, "w", "S. Gregório Nazianzeno, Bispo, Confessor e Doutor"]],
    "05-10": [[3, "w", "S. Antonino, Bispo e Confessor"], [0, "r", "Ss. Gordiano e Epímaco, Mártires"]],
    "05-11": [[2, "r", "Ss. Filipe e Tiago, Apóstolos"]],
    "05-12": [[3, "r", "Ss. Nereu, Aquileu, Domitila e Pancrácio, Mártires"]],
    "05-13": [[3, "w", "S. Roberto Belarmino, Bispo, Confessor e Doutor"]],
    "05-14": [[0, "r", "S. Bonifácio, Mártir"]],
    "05-15": [[3, "w", "S. João Batista de la Salle, Confessor"]],
    "05-16": [[0, "w", "S. Ubaldo, Bispo e Confessor"]],
    "05-17": [[3, "w", "S. Pascoal Bailão, Confessor"]],
    "05-18": [[0, "r", "S. Venâncio, Mártir"]],
    "05-19": [[3, "w", "S. Pedro Celestino, Papa e Confessor"], [0, "w", "S. Pudenciana, Virgem"]],
    "05-20": [[3, "w", "S. Bernardino de Sena, Confessor"]],
    "05-25": [[3, "w", "S. Gregório VII, Papa e Confessor"], [0, "r", "S. Urbano I, Papa e Mártir"]],
    "05-26": [[3, "w", "S. Filipe Néri, Confessor"], [0, "r", "S. Eleutério, Papa e Mártir"]],
    "05-27": [[3, "w", "S. Beda, o Venerável, Confessor e Doutor"], [0, "r", "S. João I, Papa e Mártir"]],
    "05-28": [[3, "w", "S. Agostinho de Cantuária, Bispo e Confessor"]],
    "05-29": [[3, "w", "S. Maria Madalena de Pazzi, Virgem"]],
    "05-30": [[0, "r", "S. Félix I, Papa e Mártir"]],
    "05-31": [[2, "w", "Bem-aventurada Virgem Maria Rainha"], [0, "w", "S. Petronila, Virgem"]],

    // ───────────── JUNHO ─────────────
    "06-01": [[3, "w", "S. Ângela Mérici, Virgem"]],
    "06-02": [[0, "r", "Ss. Marcelino, Pedro e Erasmo, Mártires"]],
    "06-04": [[3, "w", "S. Francisco Caracciolo, Confessor"]],
    "06-05": [[3, "r", "S. Bonifácio, Bispo e Mártir"]],
    "06-06": [[3, "w", "S. Norberto, Bispo e Confessor"]],
    "06-09": [[0, "r", "Ss. Primo e Feliciano, Mártires"]],
    "06-10": [[3, "w", "S. Margarida, Rainha, Viúva"]],
    "06-11": [[3, "r", "S. Barnabé, Apóstolo"]],
    "06-12": [[3, "w", "S. João de São Facundo, Confessor"], [0, "r", "Ss. Basílides, Cirino, Nabor e Nazário, Mártires"]],
    "06-13": [[3, "w", "S. Antônio de Pádua, Confessor e Doutor"]],
    "06-14": [[3, "w", "S. Basílio Magno, Bispo, Confessor e Doutor"]],
    "06-15": [[0, "r", "Ss. Vito, Modesto e Crescência, Mártires"]],
    "06-17": [[3, "w", "S. Gregório Barbarigo, Bispo e Confessor"]],
    "06-18": [[3, "w", "S. Efrém, Diácono, Confessor e Doutor"], [0, "r", "Ss. Marcos e Marceliano, Mártires"]],
    "06-19": [[3, "w", "S. Juliana Falconieri, Virgem"], [0, "r", "Ss. Gervásio e Protásio, Mártires"]],
    "06-20": [[0, "r", "S. Silvério, Papa e Mártir"]],
    "06-21": [[3, "w", "S. Luís Gonzaga, Confessor"]],
    "06-22": [[3, "w", "S. Paulino, Bispo e Confessor"]],
    "06-23": [[2, "v", "Vigília da Natividade de S. João Batista", "V"]],
    "06-24": [[1, "w", "Natividade de S. João Batista"]],
    "06-26": [[3, "r", "Ss. João e Paulo, Mártires"]],
    "06-28": [[2, "v", "Vigília dos Ss. Pedro e Paulo, Apóstolos", "V"], [3, "r", "S. Ireneu, Bispo e Mártir"]],
    "06-29": [[1, "r", "Ss. Pedro e Paulo, Apóstolos"]],
    "06-30": [[3, "r", "Comemoração de S. Paulo, Apóstolo"]],

    // ───────────── JULHO ─────────────
    "07-01": [[1, "r", "Preciosíssimo Sangue de Nosso Senhor Jesus Cristo", "L"]],
    "07-02": [[2, "w", "Visitação da Bem-aventurada Virgem Maria"], [0, "r", "Ss. Processo e Martiniano, Mártires"]],
    "07-03": [[3, "w", "S. Leão II, Papa e Confessor"]],
    "07-05": [[3, "w", "S. Antônio Maria Zaccaria, Confessor"]],
    "07-07": [[3, "w", "Ss. Cirilo e Metódio, Bispos e Confessores"]],
    "07-08": [[3, "w", "S. Isabel, Rainha de Portugal, Viúva"]],
    "07-10": [[3, "r", "Os Sete Santos Irmãos, Mártires, e Ss. Rufina e Segunda, Virgens e Mártires"]],
    "07-11": [[0, "r", "S. Pio I, Papa e Mártir"]],
    "07-12": [[3, "w", "S. João Gualberto, Abade"], [0, "r", "Ss. Nabor e Félix, Mártires"]],
    "07-14": [[3, "w", "S. Boaventura, Bispo, Confessor e Doutor"]],
    "07-15": [[3, "w", "S. Henrique, Imperador e Confessor"]],
    "07-16": [[0, "w", "Comemoração de Nossa Senhora do Monte Carmelo"]],
    "07-17": [[0, "w", "S. Aleixo, Confessor"]],
    "07-18": [[3, "w", "S. Camilo de Lellis, Confessor"], [0, "r", "S. Sinforosa e seus sete filhos, Mártires"]],
    "07-19": [[3, "w", "S. Vicente de Paulo, Confessor"]],
    "07-20": [[3, "w", "S. Jerônimo Emiliani, Confessor"], [0, "r", "S. Margarida, Virgem e Mártir"]],
    "07-21": [[3, "w", "S. Lourenço de Bríndisi, Confessor e Doutor"], [0, "w", "S. Praxedes, Virgem"]],
    "07-22": [[3, "w", "S. Maria Madalena, Penitente"]],
    "07-23": [[3, "r", "S. Apolinário, Bispo e Mártir"], [0, "w", "S. Libório, Bispo e Confessor"]],
    "07-24": [[0, "r", "S. Cristina, Virgem e Mártir"]],
    "07-25": [[2, "r", "S. Tiago, Apóstolo"], [0, "r", "S. Cristóvão, Mártir"]],
    "07-26": [[2, "w", "S. Ana, Mãe da Bem-aventurada Virgem Maria"]],
    "07-27": [[0, "r", "S. Pantaleão, Mártir"]],
    "07-28": [[3, "r", "Ss. Nazário, Celso, Vítor I e Inocêncio I, Mártires e Papas"]],
    "07-29": [[3, "w", "S. Marta, Virgem"], [0, "r", "Ss. Félix, Simplício, Faustino e Beatriz, Mártires"]],
    "07-30": [[0, "r", "Ss. Abdon e Senén, Mártires"]],
    "07-31": [[3, "w", "S. Inácio de Loyola, Confessor"]],

    // ───────────── AGOSTO ─────────────
    "08-01": [[0, "r", "Os Santos Macabeus, Mártires"]],
    "08-02": [[3, "w", "S. Afonso Maria de Ligório, Bispo, Confessor e Doutor"], [0, "r", "S. Estêvão I, Papa e Mártir"]],
    "08-04": [[3, "w", "S. Domingos, Confessor"]],
    "08-05": [[3, "w", "Dedicação de Santa Maria das Neves"]],
    "08-06": [[2, "w", "Transfiguração de Nosso Senhor Jesus Cristo", "L"], [0, "r", "Ss. Sisto II, Papa, Felicíssimo e Agapito, Mártires"]],
    "08-07": [[3, "w", "S. Caetano, Confessor"], [0, "r", "S. Donato, Bispo e Mártir"]],
    "08-08": [[3, "w", "S. João Maria Vianney, Confessor"], [0, "r", "Ss. Ciríaco, Largo e Esmaragdo, Mártires"]],
    "08-09": [[3, "v", "Vigília de S. Lourenço", "V"], [0, "r", "S. Romano, Mártir"]],
    "08-10": [[2, "r", "S. Lourenço, Mártir"]],
    "08-11": [[0, "r", "Ss. Tibúrcio e Susana, Mártires"]],
    "08-12": [[3, "w", "S. Clara, Virgem"]],
    "08-13": [[0, "r", "Ss. Hipólito e Cassiano, Mártires"]],
    "08-14": [[2, "v", "Vigília da Assunção da Bem-aventurada Virgem Maria", "V"], [0, "w", "S. Eusébio, Confessor"]],
    "08-15": [[1, "w", "Assunção da Bem-aventurada Virgem Maria"]],
    "08-16": [[2, "w", "S. Joaquim, Pai da Bem-aventurada Virgem Maria, Confessor"]],
    "08-17": [[3, "w", "S. Jacinto, Confessor"]],
    "08-18": [[0, "r", "S. Agapito, Mártir"]],
    "08-19": [[3, "w", "S. João Eudes, Confessor"]],
    "08-20": [[3, "w", "S. Bernardo, Abade e Doutor"]],
    "08-21": [[3, "w", "S. Joana Francisca Frémiot de Chantal, Viúva"]],
    "08-22": [[2, "w", "Imaculado Coração da Bem-aventurada Virgem Maria"], [0, "r", "Ss. Timóteo, Hipólito e Sinforiano, Mártires"]],
    "08-23": [[3, "w", "S. Filipe Benício, Confessor"]],
    "08-24": [[2, "r", "S. Bartolomeu, Apóstolo"]],
    "08-25": [[3, "w", "S. Luís, Rei e Confessor"]],
    "08-26": [[0, "r", "S. Zeferino, Papa e Mártir"]],
    "08-27": [[3, "w", "S. José de Calasanz, Confessor"]],
    "08-28": [[3, "w", "S. Agostinho, Bispo, Confessor e Doutor"], [0, "r", "S. Hermes, Mártir"]],
    "08-29": [[3, "r", "Degolação de S. João Batista"], [0, "r", "S. Sabina, Mártir"]],
    "08-30": [[3, "w", "S. Rosa de Lima, Virgem"], [0, "r", "Ss. Félix e Adauto, Mártires"]],
    "08-31": [[3, "w", "S. Raimundo Nonato, Confessor"]],

    // ───────────── SETEMBRO ─────────────
    "09-01": [[0, "w", "S. Egídio, Abade"], [0, "r", "Os Doze Santos Irmãos, Mártires"]],
    "09-02": [[3, "w", "S. Estêvão, Rei e Confessor"]],
    "09-03": [[3, "w", "S. Pio X, Papa e Confessor"]],
    "09-05": [[3, "w", "S. Lourenço Justiniano, Bispo e Confessor"]],
    "09-08": [[2, "w", "Natividade da Bem-aventurada Virgem Maria"], [0, "r", "S. Adriano, Mártir"]],
    "09-09": [[0, "r", "S. Gorgônio, Mártir"]],
    "09-10": [[3, "w", "S. Nicolau de Tolentino, Confessor"]],
    "09-11": [[0, "r", "Ss. Proto e Jacinto, Mártires"]],
    "09-12": [[3, "w", "Santíssimo Nome de Maria"]],
    "09-14": [[2, "r", "Exaltação da Santa Cruz", "L"]],
    "09-15": [[2, "w", "Sete Dores da Bem-aventurada Virgem Maria"], [0, "r", "S. Nicomedes, Mártir"]],
    "09-16": [[3, "r", "Ss. Cornélio, Papa, e Cipriano, Bispo, Mártires"], [0, "r", "Ss. Eufêmia, Lúcia e Geminiano, Mártires"]],
    "09-17": [[0, "w", "Impressão das Chagas de S. Francisco"]],
    "09-18": [[3, "w", "S. José de Cupertino, Confessor"]],
    "09-19": [[3, "r", "S. Januário, Bispo, e Companheiros, Mártires"]],
    "09-20": [[0, "r", "S. Eustáquio e Companheiros, Mártires"]],
    "09-21": [[2, "r", "S. Mateus, Apóstolo e Evangelista"]],
    "09-22": [[3, "w", "S. Tomás de Vilanova, Bispo e Confessor"], [0, "r", "S. Maurício e Companheiros, Mártires"]],
    "09-23": [[3, "r", "S. Lino, Papa e Mártir"], [0, "r", "S. Tecla, Virgem e Mártir"]],
    "09-24": [[0, "w", "Nossa Senhora das Mercês"]],
    "09-26": [[0, "r", "Ss. Cipriano e Justina, Mártires"]],
    "09-27": [[3, "r", "Ss. Cosme e Damião, Mártires"]],
    "09-28": [[3, "r", "S. Venceslau, Duque e Mártir"]],
    "09-29": [[1, "w", "Dedicação de S. Miguel Arcanjo"]],
    "09-30": [[3, "w", "S. Jerônimo, Presbítero, Confessor e Doutor"]],

    // ───────────── OUTUBRO ─────────────
    "10-01": [[0, "w", "S. Remígio, Bispo e Confessor"]],
    "10-02": [[3, "w", "Santos Anjos da Guarda"]],
    "10-03": [[3, "w", "S. Teresa do Menino Jesus, Virgem"]],
    "10-04": [[3, "w", "S. Francisco de Assis, Confessor"]],
    "10-05": [[0, "r", "Ss. Plácido e Companheiros, Mártires"]],
    "10-06": [[3, "w", "S. Bruno, Confessor"]],
    "10-07": [[2, "w", "Nossa Senhora do Rosário"], [0, "w", "S. Marcos, Papa e Confessor"]],
    "10-08": [[3, "w", "S. Brígida, Viúva"], [0, "r", "Ss. Sérgio, Baco, Marcelo e Apuleio, Mártires"]],
    "10-09": [[3, "w", "S. João Leonardi, Confessor"], [0, "r", "Ss. Dionísio, Bispo, Rústico e Eleutério, Mártires"]],
    "10-10": [[3, "w", "S. Francisco de Borja, Confessor"]],
    "10-11": [[2, "w", "Maternidade da Bem-aventurada Virgem Maria"]],
    "10-13": [[3, "w", "S. Eduardo, Rei e Confessor"]],
    "10-14": [[3, "r", "S. Calisto I, Papa e Mártir"]],
    "10-15": [[3, "w", "S. Teresa de Jesus, Virgem"]],
    "10-16": [[3, "w", "S. Edviges, Viúva"]],
    "10-17": [[3, "w", "S. Margarida Maria Alacoque, Virgem"]],
    "10-18": [[2, "r", "S. Lucas, Evangelista"]],
    "10-19": [[3, "w", "S. Pedro de Alcântara, Confessor"]],
    "10-20": [[3, "w", "S. João Câncio, Confessor"]],
    "10-21": [[0, "w", "S. Hilarião, Abade"], [0, "r", "S. Úrsula e Companheiras, Virgens e Mártires"]],
    "10-23": [[3, "w", "S. Antônio Maria Claret, Bispo e Confessor"]],
    "10-24": [[3, "w", "S. Rafael Arcanjo"]],
    "10-25": [[0, "r", "Ss. Crisanto e Daria, Mártires"]],
    "10-26": [[0, "r", "S. Evaristo, Papa e Mártir"]],
    "10-28": [[2, "r", "Ss. Simão e Judas, Apóstolos"]],

    // ───────────── NOVEMBRO ─────────────
    "11-01": [[1, "w", "Todos os Santos"]],
    "11-02": [[1, "b", "Comemoração de Todos os Fiéis Defuntos", "AD"]],
    "11-04": [[3, "w", "S. Carlos Borromeu, Bispo e Confessor"], [0, "r", "Ss. Vital e Agrícola, Mártires"]],
    "11-08": [[0, "r", "Os Santos Quatro Coroados, Mártires"]],
    "11-09": [[2, "w", "Dedicação da Arquibasílica do Santíssimo Salvador", "L"], [0, "r", "S. Teodoro, Mártir"]],
    "11-10": [[3, "w", "S. André Avelino, Confessor"], [0, "r", "Ss. Trifão, Respício e Ninfa, Mártires"]],
    "11-11": [[3, "w", "S. Martinho, Bispo e Confessor"], [0, "r", "S. Menas, Mártir"]],
    "11-12": [[3, "r", "S. Martinho I, Papa e Mártir"]],
    "11-13": [[3, "w", "S. Diogo, Confessor"]],
    "11-14": [[3, "r", "S. Josafá, Bispo e Mártir"]],
    "11-15": [[3, "w", "S. Alberto Magno, Bispo, Confessor e Doutor"]],
    "11-16": [[3, "w", "S. Gertrudes, Virgem"]],
    "11-17": [[3, "w", "S. Gregório Taumaturgo, Bispo e Confessor"]],
    "11-18": [[3, "w", "Dedicação das Basílicas dos Ss. Pedro e Paulo"]],
    "11-19": [[3, "w", "S. Isabel da Hungria, Viúva"], [0, "r", "S. Ponciano, Papa e Mártir"]],
    "11-20": [[3, "w", "S. Félix de Valois, Confessor"]],
    "11-21": [[3, "w", "Apresentação da Bem-aventurada Virgem Maria"]],
    "11-22": [[3, "r", "S. Cecília, Virgem e Mártir"]],
    "11-23": [[3, "r", "S. Clemente I, Papa e Mártir"], [0, "r", "S. Felicidade, Mártir"]],
    "11-24": [[3, "w", "S. João da Cruz, Confessor e Doutor"], [0, "r", "S. Crisógono, Mártir"]],
    "11-25": [[3, "r", "S. Catarina de Alexandria, Virgem e Mártir"]],
    "11-26": [[3, "w", "S. Silvestre, Abade"], [0, "r", "S. Pedro de Alexandria, Bispo e Mártir"]],
    "11-29": [[0, "r", "S. Saturnino, Mártir"]],
    "11-30": [[2, "r", "S. André, Apóstolo"]],

    // ───────────── DEZEMBRO ─────────────
    "12-02": [[3, "r", "S. Bibiana, Virgem e Mártir"]],
    "12-03": [[3, "w", "S. Francisco Xavier, Confessor"]],
    "12-04": [[3, "w", "S. Pedro Crisólogo, Bispo, Confessor e Doutor"], [0, "r", "S. Bárbara, Virgem e Mártir"]],
    "12-05": [[0, "w", "S. Sabas, Abade"]],
    "12-06": [[3, "w", "S. Nicolau, Bispo e Confessor"]],
    "12-07": [[3, "w", "S. Ambrósio, Bispo, Confessor e Doutor"]],
    "12-08": [[1, "w", "Imaculada Conceição da Bem-aventurada Virgem Maria", "IC"]],
    "12-10": [[0, "r", "S. Melquíades, Papa e Mártir"]],
    "12-11": [[3, "w", "S. Dâmaso I, Papa e Confessor"]],
    "12-13": [[3, "r", "S. Lúcia, Virgem e Mártir"]],
    "12-16": [[3, "r", "S. Eusébio, Bispo e Mártir"]],
    "12-21": [[2, "r", "S. Tomé, Apóstolo"]],
    "12-26": [[2, "r", "S. Estêvão, Protomártir"]],
    "12-27": [[2, "w", "S. João, Apóstolo e Evangelista"]],
    "12-28": [[2, "r", "Santos Inocentes, Mártires"]],
    "12-29": [[0, "r", "S. Tomás Becket, Bispo e Mártir"]],
    "12-31": [[0, "w", "S. Silvestre I, Papa e Confessor"]]
  };

  if (typeof module !== "undefined" && module.exports) module.exports = S;
  else root.SANTORAL_1962 = S;
})(this);
